### ISSUE TITLE
Add support for variant furnaces? 

### ISSUE THREAD

**Issue by chosenhiro** [NivOridocs/heater#5]
when using the mod in  a modpack with [Variant Furnaces](https://modrinth.com/mod/variant-furnaces) the game crashes due to

java.lang.IllegalStateException: java.lang.IllegalArgumentException: Attempt to get float field "net.bananapuppy.variantfurnaces.registries.blockentities.AbstractVFurnaceBlockEntity.burnTime" with illegal data type conversion to int
	at niv.heater.ForwardingBurnerBlockEntity.getBurnTime(ForwardingBurnerBlockEntity.java:31)

**Comment by NivOridocs** [comment]
Fixed in version 3.3 :+1:
